name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_macOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Build
      run: xcodebuild build -workspace LottieUI.xcworkspace -scheme LottieUI -derivedDataPath ci_build -configuration Release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LottieUI_Mac
        path: ci_build/Build/Products/Release
  build_iOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Build
      run: xcodebuild build -workspace LottieUI.xcworkspace -scheme LottieUITouch -derivedDataPath ci_build -configuration Release -destination generic/platform=iOS
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LottieUI_iOS
        path: ci_build/Build/Products/Release-iphoneos
  build_tvOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Build
      run: xcodebuild build -workspace LottieUI.xcworkspace -scheme LottieUICouch -derivedDataPath ci_build -configuration Release -destination generic/platform=tvOS
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LottieUI_tvOS
        path: ci_build/Build/Products/Release-appletvos
