name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: xcodebuild build -workspace LottieUI.xcworkspace -scheme LottieUI -derivedDataPath ci_build -configuration Release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LottieUI_Mac
        path: ci_build/Build/Products/Release
  build_ios:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: xcodebuild build -workspace LottieUI.xcworkspace -scheme LottieUITouch -derivedDataPath ci_build -configuration Release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LottieUI_iOS
        path: ci_build/Build/Products/Release
